### ISSUE TITLE
Multitouch Bug

### ISSUE THREAD

**Issue by wsdt** [wsdt/Flying_Fishes#13]
When flying to top and then shooting or so the shooting site triggers the flying up action.

**Comment by wsdt** [comment]
Closed with commit: 71c68efcf26dc7ce7d26f5568e99818f2ffc66c0

**Comment by Solution49** [comment]
Reopen,

Bug at Flying high -> player sometimes increases y-speed, after several up and downs.

**Comment by Solution49** [comment]
Only in Emulator!
