### ISSUE TITLE
WorldActivity: List multiple times changed

### ISSUE THREAD

**Issue by wsdt** [wsdt/Flying_Fishes#45]
- In WorldActivity we have now animations (e.g. by Backgroundlayers). By starting a level and going back to the WorldActivity the layers seem to be added one more time than before. 
- E.g. if I added as BgLayer only 3 Flying Elements, I only want 3 elements and not on the back btn 6, then 9, then 12. 
- No idea currently, I am tired. 
- WorldActivity.class, WorldManager.class, World.class, World_Earth.class

**Comment by Solution49** [comment]
This one's serious, and is yet to be done.
